### ISSUE TITLE
Zebra Plugin

### ISSUE THREAD

**Issue by pdl-services** [SergeoLacruz/inventree-zebra-plugin#1]
When i try to install the zebra plugin with pip install git+https://github.com/SergeoLacruz/inventree-zebra-plugin

I get asked for a username and password

any help

Pete

**Comment by SergeoLacruz** [comment]
The repo os public. I can install it even withour beeing logged into github. 
Perhaps a local password for  write access to your machine?
Anybody else having this issue?

**Comment by SergeoLacruz** [comment]
No problem found
