### ISSUE TITLE
USB connection need to be connected to the host machine where inventree was installed ? 

### ISSUE THREAD

**Issue by Tomaaso** [SergeoLacruz/inventree-zebra-plugin#2]
Hi, 

I'm regarding to purchase a label printer to work with inventree. 
But i'm questionning for a USB connection, if we need to connect the printer on the host machine where inventree is instaled ? 
Or we can connect the printer in USB on a client machine ? 

Regards.

Thomas.

**Comment by SergeoLacruz** [comment]
Hi,
A USB device is usually a local device and needs to be connected to the machine where Inventree runs. If you need to place the printer elsewhere think about a printer with an Ethernet interface. The driver supports both. 
If you already have a USB printer or want to save cost you can connect a USB printer on another computer and start a service there that open an Ethernet port and sends the received data to the USB port. A Raspberry is just fine, even an old one. See the file server.py for a very simple example that I use during testing for exactly that purpose. 

MIchael

**Comment by Tomaaso** [comment]
Thank you for your quick and clear response!
