### ISSUE TITLE
Question:  how to access Zebra pritner from a cloud server

### ISSUE THREAD

**Issue by tmarkson** [SergeoLacruz/inventree-zebra-plugin#3]
I have installed Inventree on a cloud server and have a Zebra printer at our warehouse.   I think this is a common scenario for Inventree users. 

My question - is it possible for the cloud server to access that Zebra printer?   The only solution I had was to use a VPN, which I'm not excited about just to enable a printer. 

I would appreciate thoughts towards a solution; maybe I'm missing the simple answer. Thanks
Ted

**Comment by SergeoLacruz** [comment]
Hmmmm....
Never thought about that. The server needs to have access to the printer. No way around. The server is somewhere, the printer on you desk. Perhaps the server can store the printout on the in some place of the server and the printer can pull it from there if you trigger a button on the printer. Anybody having a better idea?

**Comment by tmarkson** [comment]
> The server needs to have access to the printer. No way around. 

Thanks for this, it validates I wasn't missing something simple. 

> Anybody having a better idea?

When I get the time, I would connect the cloud server to my warehouse LAN via VPN; easy with wireguard.  That would allow the server to see the printer thru the tunnel.  It takes time to setup the peers;  I'll report back if I ever implement that. 

Other (easier) ideas welcome!

**Comment by DasenB** [comment]
I am facing a similar problem. I was thinking about writing a plugin that sends the label via telegram/matrix. A raspberry pi which is connected to the printer and runs a script acting as telegram-bot could then execute the print-job.

**Comment by tmarkson** [comment]
> plugin that sends the label via telegram/matrix

I also use matrix so it would suit my needs!
