### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by wolflu05** [SergeoLacruz/inventree-zebra-plugin#5]
Hello Michael,

I'm using your plugin now with my zebra printer, but after installing it, InvenTree gets significantly slower while starting because it first checks and installs the plugins from the `plugins.txt` file. However this process is really slow with plugins that are provided via git, because the repo needs to be first cloned to see if there is a new version or not. For testing purposes and experimental plugins this is a great setup. Are you planning on also publishing this plugin on a python package registry like pypi?

Best
Lukas

**Comment by SergeoLacruz** [comment]
Hi,
I installed it directly on the server using pip. So I never had this probem.  I did not work with pypi so far but it is a good idea anyway.  Will take some days. 

Michael

**Comment by wolflu05** [comment]
Hi, thanks for that quick reply, good to know, if you need any help setting it up, let me know. What I do for my plugins is basically [this workflow](https://github.com/wolflu05/inventree-dymo-plugin/blob/main/.github/workflows/ci.yml). Then you only need to configure a new pending publishing entry on pypi with the correct repo and there is no need for any token, because gh actions can authenticate with pypi directly and can verify that this request is coming from your repo.

**Comment by SergeoLacruz** [comment]
Hi,
Should be done now. Give it a try.
Michael

**Comment by wolflu05** [comment]
Thank you very much 🚀 , its working and the staring process is much faster now.
