### ISSUE TITLE
updated from 0.3.1 to 0.5.1 lots of issues

### ISSUE THREAD

**Issue by anonkwe** [SergeoLacruz/inventree-zebra-plugin#7]
is there any way that i can get my hands on the plugin 0.3.1 ? since I've upgraded it to the latest issue, the quality lowered drastically, and I mean by a mile, It's havind difficulties printing since it seems that the plugin manages way more the printer than it used to. It also looks like there was way too much pressure applied while printing QR codes or big characters. see attached picutre: on top is the 0.5.1 ones, below them, its the ones generated in 0.3.1

 

![image](https://github.com/SergeoLacruz/inventree-zebra-plugin/assets/61838766/c929d182-e574-45de-8a1c-73a8ca70da4f)

**Comment by SergeoLacruz** [comment]
Hi,
You are free to download and install 0.3.0 from releases. 
The major difference in functionality between 0.3.0 and 0.5.1 is the new initial sequence in the printer settings that allows you tu
setup the printer. There is a default setting that fits fine for my printer. It might be different for your printer. So please have a look there.
If the print gets too dark you can reduce the darkness value in the settings. Hope that helps.

Michael

**Comment by anonkwe** [comment]
is there any way to have 0.3.1 back man?

**Comment by anonkwe** [comment]
![image](https://github.com/SergeoLacruz/inventree-zebra-plugin/assets/61838766/c5a5b97c-37b9-42bd-9f46-67820d18b007)
the dot per mm optuion does not seem usable.

**Comment by anonkwe** [comment]
ok, i figured it all out. it's all working good now. I got another question tho, is there any way to get multiple printers to work with the plugin?

**Comment by SergeoLacruz** [comment]
Kaum macht mans richtig... :-)
Nice to hear that the plugin works fine for you now. Multiple printers cannot be used withthis plugin. The 
inventree interface is not really made for this. The new machine interface available in 0.14.0 is made for this.
In #6  is already a request for this plugin to use the new interface but I did not start this so far.

**Comment by anonkwe** [comment]
Is there any way to tweak it so that i can install the plugin twice as if
the environment would think this is a different plugin?

**Comment by SergeoLacruz** [comment]
I think we can close this.
