### ISSUE TITLE
Cannot print over vpn

### ISSUE THREAD

**Issue by Philipboy881** [SergeoLacruz/inventree-zebra-plugin#9]
I have a zebra printer I can print from the local network without any problem. But the problem starts when I move the printer behind an vpn tunnel on a remote location.

I had Inventree 16.1 running without any problem and after upgrading to 17.0 I cannot print anything. After downgrading it worked again (I have a snapshot of the vm)

On 17.0 version 7 of the print plugin is installed

I can ping the printer on the remote network. I can see the homepage of the printer from the server.

When I print a label I see the green led blink on the printer and when I look at the job log I can see the job was received.

Any suggestions are welcome

**Comment by SergeoLacruz** [comment]
Continuing the discussion from 
https://github.com/inventree/InvenTree/issues/8740

This seems to be more related to socket / VPN than InvenTree. I would suggest to write a few lines of python code that send a file to the printer. This is easier to debug.

**Comment by SergeoLacruz** [comment]
Small file works. Great.
Inventree HTML templates are converted to bitmap and send to the printer which results in large files. About 35k using your
template which is much larger than ours. Please try to raise the timeout

https://github.com/SergeoLacruz/inventree-zebra-plugin/blob/dd8bfaa23c7b9d3cdb1718436af05d261517e024/inventree_zebra/zebra_plugin.py#L167C16-L167C39

Or just remove it for the moment. 

Michael

**Comment by Philipboy881** [comment]
after disabling the timout with a # it did work. is it posible to include this value in the settings menu of inventree?
0 = disable and any other number as the set value?

**Comment by SergeoLacruz** [comment]
Congratulations. Good to hear that it works now. I will enlarge the value in future releases. Removing the timeout might result in a hanging process. 
You can drastically reduce the file size when you use ZPL templates. They render in the printer. See docs. 
Have a nice Christmas :-)

**Comment by SergeoLacruz** [comment]
I changed send to sendall. This results in a timeout error in case a timeout occurs.
